#

---

- name: Install Steam Game
  hosts: "*steam-servers"
  user: root

  vars:
    games_dict:
      squad: 403240
      hellion: 598850
      7days: 294420

  tasks:

    # install game dir
    - name: Create Game Directory
      file:
        path: /home/steam/steam/games/{{ item }}
        state: directory
        owner: steam
        group: steam
      with_items: "{{ games.split(',') }}"

    # create update script for games
    - name: Create update script for games
      template: 
        src: templates/steam/update-server.sh.j2
        dest: /home/steam/steam/update-{{ item }}.sh
        owner: steam
        group: steam
        mode: 0755
      with_items: "{{ games.split(',') }}"