#

---

- name: Install Steam Game
  hosts: "*steam-servers"
  user: root

  vars:
    start_servers: false
    games_dict:
      squad: 403240
      hellion: 598850
      7days: 294420

  tasks:

    # install game dir
    - name: Create Game Directory
      file:
        path: /home/steam/steam/games/{{ item }}
        state: directory
        owner: steam
        group: steam
      with_items: "{{ games.split(',') }}"

    # create update script for games
    - name: Create update script for games
      template: 
        src: templates/steam/update-server.sh.j2
        dest: /home/steam/steam/update-{{ item }}.sh
        owner: steam
        group: steam
        mode: 0755
      with_items: "{{ games.split(',') }}"

    # install/update game
    # successful install = Success! App '403240' fully installed.
    - name: Install/Update games
      shell: /home/steam/steam/update-{{ item }}.sh
      register: install_games
      with_items: "{{ games.split(',') }}"

    - debug: var=install_games